# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My private public notes
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Notes on software engineering including testing tools and frameworks,
  code snippets and other stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://michalsi.github.io" # the base hostname & protocol for your site

github_username:  michalsi

gems: [jekyll-paginate]

paginate: 5
paginate_path: "/page-:num/"

# Build settings
markdown: kramdown
